name: Notificacao de Deploy no Discord

on:
  # Gatilho: Roda sempre que houver um push na branch main
  push:
    branches:
      - main

jobs:
  notificar:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar notificacao para o Discord
        uses: rjstone/discord-webhook-notify@v1
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          # Colocamos a descrição numa única linha, usando \n para a quebra de linha.
          # Isto evita problemas de formatação do YAML.
          description: "**✅ Novo Deploy em Produção**\nO código foi atualizado na branch 'main' com sucesso! Deploy iniciado."
          color: "32768"