name: Notificacao de Deploy no Discord

on:
  push:
    branches:
      - main

jobs:
  notificar:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar notificação para o Discord
        uses: appleboy/discord-action@master
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          message: |
            ✅ **Novo Deploy em Produção**
            **Commit:** ${{ github.event.head_commit.message }}
            **Autor:** ${{ github.actor }}
            **Hash:** `${{ github.sha }}`
            O deploy foi iniciado com sucesso na branch `main`.