name: Notificacao de Deploy no Discord

on:
  # Gatilho: Roda sempre que houver um push na branch main
  push:
    branches:
      - main

jobs:
  notificar:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar notificacao para o Discord
        uses: rjstone/discord-webhook-notify@v1
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          # Colocamos o "título" como a primeira linha da descrição, usando Markdown para negrito.
          description: |
            **✅ Novo Deploy em Produção**
            O código foi atualizado na branch 'main' com sucesso! Deploy iniciado.
          color: "32768" # Cor verde em formato decimal